Feature 1
Gimbalgal/travel-website pull request #1
Opened 2024-10-15 11:25 UTC by Gimbalgal

Design a mobile view of a traveling website. I am sending a pull request for evaluation and correction.

Thank you.

2024-10-18 14:37 UTC, Devsalmasaeed approved these changes
Hi @Gimbalgal,

Your project is complete! There is nothing else to say other than... it's time to merge it!!!
Congratulations! 🎉

<div style="text-align:center;">
    <img src="https://media1.giphy.com/media/gLu90OMjz4j3hAkJk2/giphy.gif?cid=47028fa8sx12d824xrvy8zo8bq3w00f23hoj11gqqzus7q0f&ep=v1_gifs&rid=giphy.gif&ct=g" alt="Remote Collaboration" style="width:100%;">
</div>

### Highlights
- ✅ **Professional Readme**
- ✅ **Good use of Gitflow**
- ✅ **UI looks like the Figma design**
- ✅ **Good use of HTML semantics**
- ✅ **Professional commit messages**
- ✅ **Professional PR title**
- ✅ **Professional PR description**

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

2024-10-18 14:37 UTC, Devsalmasaeed commented on index.html
> +    <div class="Sunter Lake ">
- Remove white space in your code

2024-10-18 14:37 UTC, Devsalmasaeed commented on index.html
> +
- Remove white space

2024-10-18 14:37 UTC, Devsalmasaeed commented on index.html
> +<div class="footer">
- Remove white space

2024-10-18 18:57 UTC, Xfarouq commented on index.html
> +        <div class="nav">
Avoid leaving spaces in your code for best practices

2024-10-18 19:00 UTC, Xfarouq requested changes
Hi @username,

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    <img src="https://camo.githubusercontent.com/7cf1ba8db9cd08f454a9651e48128c064a4440a59881658c8593a41a8de243f3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966" alt="Remote Collaboration" style="width:40%;">
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️

- Please make the section below to be centrally aligned with the whole website to avoid it overflowing (i. e moving horizontally left to right)
- 
![image](https://github.com/user-attachments/assets/a2afbf4f-188f-4827-aca5-ee6a895c4e52)


### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

2024-10-21 13:35 UTC, Devsalmasaeed approved these changes
> Hi @Gimbalgal,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it!!! Congratulations! 🎉
> 
> ![Remote Collaboration](https://camo.githubusercontent.com/636f8f83cc9fdf8edaad0e2e31e471335a0431c15559750d6ff98dc325075ca5/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f674c7539304f4d6a7a346a3368416b4a6b322f67697068792e6769663f6369643d3437303238666138737831326438323478727679387a6f38627133773030663233686f6a31316771717a7573377130662665703d76315f67696673267269643d67697068792e6769662663743d67)
> ### Highlights
> * ✅ **Professional Readme**
> * ✅ **Good use of Gitflow**
> * ✅ **UI looks like the Figma design**
> * ✅ **Good use of HTML semantics**
> * ✅ **Professional commit messages**
> * ✅ **Professional PR title**
> * ✅ **Professional PR description**
> 
> ### Optional Suggestions
> Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.
> 
> Cheers and Happy coding! 👏👏👏
> 
> _Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification._

2024-10-21 13:36 UTC, merged